### ISSUE TITLE
add support for IDEA 2023.*

### ISSUE THREAD

**Issue by SaymonPhoenix** [spetriuk/sops-intellij-plugin#7]
Please add support for IDEA 2023.*. After updating I get an error that the plugin is not supported.
![image](https://user-images.githubusercontent.com/34863553/231747043-f62f72d1-3320-47f9-aa32-78015679ab79.png)

**Comment by holzerch** [comment]
Created a PR for this https://github.com/spetriuk/sops-intellij-plugin/pull/8

**Comment by SaymonPhoenix** [comment]
> Created a PR for this #8

Thanks a lot. If you help me make a build and install it in IDEA, then I will be very grateful to you.

**Comment by holzerch** [comment]
This is the build result in case you want to manually install it
[sops-intellij-plugin-1.1.4-alpha.zip](https://github.com/spetriuk/sops-intellij-plugin/files/12123663/sops-intellij-plugin-1.1.4-alpha.zip)

**Comment by SaymonPhoenix** [comment]
> This is the build result in case you want to manually install it [sops-intellij-plugin-1.1.4-alpha.zip](https://github.com/spetriuk/sops-intellij-plugin/files/12123663/sops-intellij-plugin-1.1.4-alpha.zip)

A mug of beer for this gentleman.
Thank you very much from Mother Russia.

**Comment by spetriuk** [comment]
Thanks for the contribution, @holzerch. Apologies for the late merge.
